version: "3.8"
services:
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - ./grafana-datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
      - grafana-storage:/var/lib/grafana

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.enable-remote-write-receiver'
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-storage:/prometheus

  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    volumes:
      - loki-storage:/loki

  tempo:
    image: grafana/tempo:latest
    # hostname: tempo
    user: "root" # Add this line to fix permmission issues
    ports:
      - "3200:3200" # tempo
      - "4317:4317" # otlp grpc
      - "4318:4318" # otlp http
    command: ["-target=all", "-config.file=/etc/tempo.yml"]
    volumes:
      - ./tempo-config.yml:/etc/tempo.yml
      - tempo-storage:/tmp/tempo

  promtail:
    image: grafana/promtail:latest
    volumes:
      - /var/log:/var/log
      - ./promtail-config.yml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml

  node-exporter:
    image: prom/node-exporter:latest
    ports:
      - "9100:9100"

  # mock-app:
  #   build: .
  #   ports:
  #     - "8000:8000" # Expose a port if your app has a web server
  #   depends_on:
  #     - loki
  #     - tempo

volumes:
  grafana-storage: {}
  prometheus-storage: {}
  loki-storage: {}
  tempo-storage: {}